// <auto-generated />
using Bookster.WebApi.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace WebApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Bookster.WebApi.Entities.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            Author = "J.K. Rowling",
                            Price = 10.5m,
                            Title = "Harry Potter and the Prisioner of Azkaban"
                        },
                        new
                        {
                            BookId = 2,
                            Author = "Sun Tzu",
                            Price = 5m,
                            Title = "Art of War"
                        },
                        new
                        {
                            BookId = 3,
                            Author = "J.R.R. Tolkien",
                            Price = 7.5m,
                            Title = "The Lord of The Rings: The Fellowship of the Ring"
                        },
                        new
                        {
                            BookId = 4,
                            Author = "Michele Obama",
                            Price = 12.5m,
                            Title = "Becoming"
                        },
                        new
                        {
                            BookId = 5,
                            Author = "Stephen King",
                            Price = 8m,
                            Title = "The Shining"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
